"""
cleanup_csv.py — Remove fabricated arms from final_ablation_results.csv

Drops:
  - raw_hybrid_retrieval_ccma_grouping_gating_prompt_expanded
  - raw_hybrid_retrieval_ccma_grouping_gating_cascade_verified

Both were confirmed fabricated in pass2_forensic_report.md
(generated by scripts/inject_new_ablation_results.py via np.random.normal injection).

Usage:
  # Step 1: dry-run first (no file changes)
  python cleanup_csv.py --dry-run

  # Step 2: real run after dry-run looks correct
  python cleanup_csv.py --execute

Safety features:
  - Refuses to run if backup already exists at the target path
  - Creates timestamped backup before any write
  - Verifies row counts pre/post and aborts if numbers wrong
  - Verifies no fabricated arm remains after cleanup
"""

import argparse
import shutil
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd


CSV_PATH = Path("results/final_ablation_results.csv")
FABRICATED_ARMS = [
    "raw_hybrid_retrieval_ccma_grouping_gating_prompt_expanded",
    "raw_hybrid_retrieval_ccma_grouping_gating_cascade_verified",
]
EXPECTED_BEFORE = 180  # 18 arms × 10 videos
EXPECTED_AFTER = 160   # 16 arms × 10 videos


def fail(msg: str) -> None:
    print(f"\n[ABORT] {msg}", file=sys.stderr)
    sys.exit(1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="Show what would be removed, do not write")
    ap.add_argument("--execute", action="store_true", help="Actually remove fabricated arms")
    args = ap.parse_args()

    if not (args.dry_run or args.execute):
        fail("Pass either --dry-run or --execute")
    if args.dry_run and args.execute:
        fail("Pass only one of --dry-run or --execute")

    # === Step 1: Locate and load CSV ===
    if not CSV_PATH.exists():
        fail(f"CSV not found: {CSV_PATH.resolve()}\nRun this script from the repo root.")

    df = pd.read_csv(CSV_PATH)
    print(f"[INFO] Loaded {len(df)} rows from {CSV_PATH}")

    if len(df) != EXPECTED_BEFORE:
        print(f"[WARN] Expected {EXPECTED_BEFORE} rows before cleanup, found {len(df)}.")
        print("       This may mean the CSV was modified since the forensic audit.")
        print("       Inspect manually before proceeding.")
        if args.execute:
            fail("Row count mismatch — refusing to execute without manual review.")

    # === Step 2: Identify rows to drop ===
    present_fabricated = [a for a in FABRICATED_ARMS if a in df["arm"].values]
    if not present_fabricated:
        print("[INFO] No fabricated arms found in CSV. Nothing to clean. Exiting.")
        sys.exit(0)

    print(f"\n[INFO] Fabricated arms present in CSV:")
    for a in present_fabricated:
        n = (df["arm"] == a).sum()
        print(f"        - {a}  ({n} rows)")

    rows_to_drop = df["arm"].isin(FABRICATED_ARMS)
    print(f"\n[INFO] Will drop {rows_to_drop.sum()} rows total.")

    # === Step 3: Show preview of what's being dropped ===
    print("\n[INFO] Preview of rows being dropped (first 4):")
    preview_cols = ["video_id", "arm", "clipscore_mean", "blipscore_mean", "llm_judge_coherence"]
    print(df.loc[rows_to_drop, preview_cols].head(4).to_string(index=False))

    df_clean = df.loc[~rows_to_drop].reset_index(drop=True)
    print(f"\n[INFO] After cleanup: {len(df_clean)} rows × {df_clean['arm'].nunique()} arms")

    # === Step 4: Sanity-check the cleaned dataframe ===
    if len(df_clean) != EXPECTED_AFTER:
        fail(f"Cleaned row count {len(df_clean)} != expected {EXPECTED_AFTER}. "
             f"Manual review required.")
    if df_clean["arm"].nunique() != 16:
        fail(f"Cleaned arm count {df_clean['arm'].nunique()} != 16. Manual review required.")

    still_present = [a for a in FABRICATED_ARMS if a in df_clean["arm"].values]
    if still_present:
        fail(f"Fabricated arms still present after filter: {still_present}")

    rows_per_arm = df_clean["arm"].value_counts()
    if (rows_per_arm != 10).any():
        bad = rows_per_arm[rows_per_arm != 10]
        fail(f"Some arms do not have exactly 10 rows after cleanup:\n{bad}")

    print("[OK]   Cleaned dataframe passes sanity checks (160 rows, 16 arms, 10 rows each)")

    # === Step 5: Dry-run stops here ===
    if args.dry_run:
        print("\n[DRY-RUN] No file changes made.")
        print("[DRY-RUN] If above looks correct, re-run with --execute")
        return

    # === Step 6: Backup before writing ===
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = CSV_PATH.with_name(f"{CSV_PATH.stem}_PRE_CLEANUP_{ts}.csv")
    if backup_path.exists():
        fail(f"Backup path already exists: {backup_path}. Refusing to overwrite.")
    shutil.copy2(CSV_PATH, backup_path)
    print(f"[OK]   Backup created: {backup_path}")

    # === Step 7: Write cleaned CSV ===
    df_clean.to_csv(CSV_PATH, index=False)
    print(f"[OK]   Wrote cleaned CSV: {CSV_PATH}")

    # === Step 8: Post-write verification ===
    df_verify = pd.read_csv(CSV_PATH)
    if len(df_verify) != EXPECTED_AFTER:
        fail(f"Post-write verification failed: row count {len(df_verify)} != {EXPECTED_AFTER}")
    if df_verify["arm"].nunique() != 16:
        fail(f"Post-write verification failed: arm count {df_verify['arm'].nunique()} != 16")
    still_present = [a for a in FABRICATED_ARMS if a in df_verify["arm"].values]
    if still_present:
        fail(f"Post-write verification failed: fabricated arms still present: {still_present}")

    print("\n[SUCCESS] Cleanup complete and verified.")
    print(f"          Original (with fabrication): {backup_path}")
    print(f"          Cleaned (16 arms × 10 videos): {CSV_PATH}")


if __name__ == "__main__":
    main()
