import pytest
from pathlib import Path
from unittest.mock import MagicMock, patch
import json
import os

from src.phase2_summarize import Phase2Summarizer
from src.models.llm_wrapper import GroqBackend, LocalBackend
from src.schemas import TranscriptSchema, SummaryScript

def load_env_manually():
    env_path = Path(".env")
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, value = line.split("=", 1)
                    os.environ[key.strip()] = value.strip().strip('"').strip("'")

load_env_manually()

@pytest.fixture
def mock_transcript_path(tmp_path):
    transcript_data = {
        "video_id": "test_video",
        "duration_seconds": 30.0,
        "language": "en",
        "segments": [
            {"id": 0, "start": 0.0, "end": 10.0, "text": "Hello world, this is a test for Phase 2 summarization."},
            {"id": 1, "start": 10.0, "end": 20.0, "text": "We are testing the LLM backend wrapper and the summarizer logic."},
            {"id": 2, "start": 20.0, "end": 30.0, "text": "The goal is to generate a concise script for a 90 second video."}
        ]
    }
    path = tmp_path / "transcript.json"
    with open(path, "w") as f:
        json.dump(transcript_data, f)
    return path

def test_summarizer_with_mock_groq(mock_transcript_path):
    # Mock return JSON
    mock_json = {
        "video_id": "test_video",
        "target_duration": 90,
        "style": "informative",
        "backend_used": "groq",
        "sentences": [
            {
                "id": 1,
                "text": "This is a test script generated by a mock backend for verification.",
                "estimated_duration_seconds": 5.5,
                "source_timestamp_hint": [0.0, 30.0],
                "keywords": ["test", "mock", "phase2"]
            }
        ]
    }
    
    mock_backend = MagicMock(spec=GroqBackend)
    # LLM might return markdown with JSON
    mock_backend.generate.return_value = f"Here is the script:\n```json\n{json.dumps(mock_json)}\n```"
    
    summarizer = Phase2Summarizer(mock_backend, {})
    output_path = summarizer.run(mock_transcript_path, target_duration=90)
    
    assert output_path.exists()
    with open(output_path, "r") as f:
        data = json.load(f)
        SummaryScript.model_validate(data)
        assert data["video_id"] == "test_video"
        assert len(data["sentences"]) == 1
        assert data["sentences"][0]["text"] == mock_json["sentences"][0]["text"]

def test_real_groq_if_key_exists(mock_transcript_path):
    # Try to get API key from environment or .env
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        # Check .env manually if load_dotenv didn't find it (common in some environments)
        env_path = Path(".env")
        if env_path.exists():
            with open(env_path) as f:
                for line in f:
                    if line.startswith("GROQ_API_KEY="):
                        api_key = line.split("=", 1)[1].strip().strip('"')
    
    if not api_key:
        pytest.skip("GROQ_API_KEY not found. Skipping real API test.")
    
    # We use a current model
    backend = GroqBackend(api_key=api_key, model_name="llama-3.3-70b-versatile")
    summarizer = Phase2Summarizer(backend, {})
    
    output_path = summarizer.run(mock_transcript_path, target_duration=90)
    assert output_path.exists()
    
    with open(output_path, "r") as f:
        data = json.load(f)
        SummaryScript.model_validate(data)
        assert "sentences" in data
        assert len(data["sentences"]) > 0
